user1 = User.find_or_create_by(account:'001',name:'Donald Superme',password:'314159',rule: 0)
user2 = User.find_or_create_by(account:'002',name:'test1',password:'123',rule: 1)
user3 = User.find_or_create_by(account:'003',name:'test2',password:'123',rule: 1)
user4 = User.find_or_create_by(account:'004',name:'test3',password:'123',rule: 1)
user5 = User.find_or_create_by(account:'005',name:'test4',password:'123',rule: 1)
user6 = User.find_or_create_by(account:'006',name:'test5',password:'123',rule: 1)

Article.find_or_create_by(title:"test1",body:"this is body",score:4.9,section:1,thumbs:50,user: user1)
Article.find_or_create_by(title:"test2",body:"this is body",score:4.9,section:2,thumbs:50,user: user2)
Article.find_or_create_by(title:"test3",body:"this is body",score:4.9,section:3,thumbs:50,user: user3)
Article.find_or_create_by(title:"test4",body:"this is body",score:4.9,section:4,thumbs:50,user: user4)
Article.find_or_create_by(title:"test5",body:"this is body",score:4.9,section:5,thumbs:50,user: user5)
Article.find_or_create_by(title:"test6",body:"this is body",score:4.9,section:6,thumbs:50,user: user6)

Article.find_or_create_by(title:"test01",body:"this is body_no2",score:4.9,section:1,thumbs:50,user: user1)
Article.find_or_create_by(title:"test02",body:"this is body_no2",score:4.9,section:2,thumbs:50,user: user2)
Article.find_or_create_by(title:"test03",body:"this is body_no2",score:4.9,section:3,thumbs:50,user: user3)
Article.find_or_create_by(title:"test04",body:"this is body_no2",score:4.9,section:4,thumbs:50,user: user4)
Article.find_or_create_by(title:"test05",body:"this is body_no2",score:4.9,section:5,thumbs:50,user: user5)
Article.find_or_create_by(title:"test06",body:"this is body_no2",score:4.9,section:6,thumbs:50,user: user6)